sudo: required
dist: jammy
group: edge
language: node_js
#language: generic
node_js:
 - "16"
services:
  - docker

# Build Docker Image
before_install:
  - docker build -t brianbeck/react-test -f ./client/Dockerfile.dev ./client

# Test Runner
script:
  - docker run -e CI=true brianbeck/react-test npm run test

# Build Docker Images
after_success:
  - docker build -t brianbeck/multi-client ./client
  - docker build -t brianbeck/multi-nginx ./nginx
  - docker build -t brianbeck/multi-server ./server
  - docker build -t brianbeck/multi-worker ./worker

# Push Docker Images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push brianbeck/multi-client
  - docker push brianbeck/multi-nginx
  - docker push brianbeck/multi-server
  - docker push brianbeck/multi-worker

# Deploy to Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket-name: "elasticbeanstalk-us-east-1-651266901933"
  bucket-path: "docker-multi"
  # only deploy on changes to master 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY